language: perl
perl:
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
addons:
   postgresql: "9.3"
env:
  - DB_TESTING=1 RELEASE_TESTING=1
before_install:
  - if [[ "$PERLBREW_PERL" == "5.24" ]]; then export COVERAGE=1 ; fi 
  - eval $(curl https://travis-perl.github.io/init) --auto

before_script:
  - coverage-setup

script:
  - make && prove -l

after_success:
  - coverage-report
